# Generated by Django 5.2 on 2025-04-21 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ชื่อลูกค้า')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='เบอร์โทรศัพท์')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='อีเมล')),
                ('visits', models.IntegerField(default=1, verbose_name='จำนวนครั้งที่มาใช้บริการ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่ลงทะเบียน')),
                ('last_visit', models.DateTimeField(auto_now=True, verbose_name='เข้าใช้บริการล่าสุด')),
            ],
            options={
                'verbose_name': 'ลูกค้า',
                'verbose_name_plural': 'ลูกค้า',
                'ordering': ['-last_visit'],
            },
        ),
    ]
