# Generated by Django 5.2 on 2025-04-27 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_updated_at_orderitem_menu_item_orderitem_price_and_more'),
    ]

    operations = [
        # This field already exists in the database, so we're making this a no-op migration
        # Just updating the model to match the database schema
    ]
